### ISSUE TITLE
MP4 - Script compilation failed on 1.11.0 update

### ISSUE THREAD

**Issue by Glocker134** [Phlarx/tm-ultimate-medals#38]
Ultimate Medals won't load on MP4 after updating to 1.11.0. ScriptEngine log shows:

```
UltimateMedals UltimateMedals.as (503, 01) : INFO : Compiling void Main()
UltimateMedals UltimateMedals.as (627, 35) :  ERR : Both operands must be handles when comparing identity
Script compilation failed!
```

**Comment by Phlarx** [comment]
Thanks for the report! The fix (commit 3e3da3c) is already in review, and will be published as soon as it's ready.
If you want to downgrade to the previous version (1.10.3), it can be downloaded from https://openplanet.dev/plugin/ultimatemedals/versions
